### ISSUE TITLE
 Can I create dynamic template for contextmenu based on some variable?

### ISSUE THREAD

**Issue by spanda90** [isaacplmann/angular2-contextmenu#45]
use a for loop to create a template for context menu

**Comment by isaacplmann** [comment]
Yes.
https://github.com/isaacplmann/angular2-contextmenu/issues/15#issuecomment-252943752

**Comment by spanda90** [comment]
Instead of contextmenuactions if I want to iterate based on item.actions.. can I do that ?

**Comment by spanda90** [comment]
Can you also provide an example if it is possible to do?

**Comment by spanda90** [comment]
I can rephrase my question: If I want a dynamic menu generated for each item, how can I do that?

**Comment by isaacplmann** [comment]
If you really have a different set of actions for each item, you'll need to create a new `<context-menu>` tag for each item in your list.

Something like this:
```html
<ul>
  <li *ngFor="let item of items" [contextMenu]="itemContextMenu" [contextMenuSubject]="item">
    {{item.name}}
    <context-menu #itemContextMenu>
      <template *ngFor="let action of item.actions" contextMenuItem let-item [visible]="action.visible" [enabled]="action.enabled"
        (execute)="action.execute($event.item)">
        {{ action.html(item) }}
        </template>
    </context-menu>
  </li>
</ul>
```

```ts
  public items: any[] = [
    {
      name: 'John', otherProperty: 'Foo', actions: [{
        enabled: true,
        execute: item => console.log(item),
        html: item => `John custom: ${item.name}`,
        visible: true,
      }],
    },
    {
      name: 'Joe', otherProperty: 'Bar', actions: [{
        enabled: true,
        execute: item => console.log(item),
        html: item => `Joe something: ${item.name}`,
        visible: true,
      }],
    },
  ];
```

The other option would be to filter actions based on properties of the item.

**Comment by spanda90** [comment]
I get this error. As the items in my case are loaded from a configuration in ngOnInit()

**Comment by spanda90** [comment]
Error in ./DashboardComponent class DashboardComponent - inline template:9:33 caused by: Expression has changed after it was checked. Previous value: 'undefined'. Current value: '[object Object]'.

**Comment by isaacplmann** [comment]
Can you send me the relevant component code?

**Comment by spanda90** [comment]
<div class='componentsContainer'>
    <div *ngFor='let component of dashboard.components;let i = index' [ngSwitch]='component.type' [ngStyle]='component.layout'
      class='componentContainer' [contextMenu]='itemContextMenu' [contextMenuSubject]='component'>
      <customtable *ngSwitchCase='"customtable"' [config]='component' [componentId]='i' [container]='dashboard'>
<context-menu #itemContextMenu>
      <template *ngFor="let action of component.actions" contextMenuItem let-item>
        {{ action.html(item) }}
        </template>
    </context-menu>
</customtable>
      <grid *ngSwitchCase='"grid"' [config]='component' [componentId]='i' [container]='dashboard'></grid>
      <heatmap *ngSwitchCase='"heatmap"' [config]='component' [componentId]='i' [container]='dashboard'></heatmap>
      <gallery *ngSwitchCase='"gallery"' [config]='component' [componentId]='i' [container]='dashboard'></gallery>
      <timeseries *ngSwitchCase='"timeseries"' [config]='component' [componentId]='i' [container]='dashboard'></timeseries>
      <topn *ngSwitchCase='"topn"' [config]='component' [componentId]='i' [container]='dashboard'></topn>
      <timeaxis *ngSwitchCase='"timeaxis"' [config]='component' [componentId]='i' [container]='dashboard'></timeaxis>
      <mask *ngSwitchCase='"mask"' [config]='component' [componentId]='i' [container]='dashboard'></mask>
    </div>
  </div>

**Comment by spanda90** [comment]
<div class='componentsContainer'>
    <div *ngFor='let component of dashboard.components;let i = index'
[ngSwitch]='component.type' [ngStyle]='component.layout'
      class='componentContainer' [contextMenu]='itemContextMenu'
[contextMenuSubject]='component'>
      <customtable *ngSwitchCase='"customtable"' [config]='component'
[componentId]='i' [container]='dashboard'>
<context-menu #itemContextMenu>
      <template *ngFor="let action of component.actions" contextMenuItem
let-item>
        {{ action.html(item) }}
        </template>
    </context-menu>
</customtable>
      <grid *ngSwitchCase='"grid"' [config]='component' [componentId]='i'
[container]='dashboard'></grid>
      <heatmap *ngSwitchCase='"heatmap"' [config]='component'
[componentId]='i' [container]='dashboard'></heatmap>
      <gallery *ngSwitchCase='"gallery"' [config]='component'
[componentId]='i' [container]='dashboard'></gallery>
      <timeseries *ngSwitchCase='"timeseries"' [config]='component'
[componentId]='i' [container]='dashboard'></timeseries>
      <topn *ngSwitchCase='"topn"' [config]='component' [componentId]='i'
[container]='dashboard'></topn>
      <timeaxis *ngSwitchCase='"timeaxis"' [config]='component'
[componentId]='i' [container]='dashboard'></timeaxis>
      <mask *ngSwitchCase='"mask"' [config]='component' [componentId]='i'
[container]='dashboard'></mask>
    </div>
  </div>

**Comment by isaacplmann** [comment]
You'll want to change `let-item` to `let-item="component"` in the template inside your context menu element, but that doesn't relate to the error you're getting.  My guess is that you're setting a value somewhere in the typescript code for the component.

Wrapping it in a setTimeout will fix it.  i.e.
```ts
setTimeout(() => this.someValue = newValue);
```

**Comment by spanda90** [comment]
Wrapping it in set Timeout also did not fix it. The context menu library does some pre checking of values before and after initialization.

**Comment by spanda90** [comment]
There was a bug in my code. Made it work.Thanks a lot for the help.

**Comment by spanda90** [comment]
Dynamic Menu problem is solved, but after moving the context menu inside the ngFor template, the position of context menu is not proper ahh

**Comment by spanda90** [comment]
As my components are all fixed positioned components and not relative.

**Comment by isaacplmann** [comment]
That sounds like a bug in my lib.  I'll work on a fix on Monday.

**Comment by spanda90** [comment]
Yeah Thanks

**Comment by isaacplmann** [comment]
I think the `position:fixed` bug is fixed in 0.7.6.  Let me know.

**Comment by spanda90** [comment]
There are some issues in installing 0.7.6 version due to unmet peer dependencies. I did not face this problem with 0.7.4 version.

**Comment by isaacplmann** [comment]
What are the peer dependencies that are unmet?  I just checked the package.json and I'm not specifying any peer dependencies.

**Comment by spanda90** [comment]
I was able to install 0.7.6 version, but still the position bug is not fixed for me

**Comment by isaacplmann** [comment]
Can you post the html structure of all the parents of <context-menu> element?

I’ll also need to know what the `position` and `transform` style attributes is of each of the ancestor elements.  So something like this would allow me to reproduce it:

<div>
  <div style=“position:relative;”>
    <div style=“position:fixed;”>
      <context-menu></context-menu>
    </div>
  </div>
</div>

**Comment by spanda90** [comment]
<body>
  <div *ngIf='dashboard' class='dashboardContainer'>
    
    <toolbar *ngIf='toolbar' [config]='toolbar'></toolbar>
    <tooltip *ngIf='tooltip' [style.visibility]='tooltip.show ?
"visible":"hidden"' [config]='tooltip'></tooltip>
    <popup *ngIf='popup && popup.components' [config]='popup'></popup>
    <second-popup *ngIf='secondpopup && secondpopup.components'
[config]='secondpopup'></second-popup>
    <messagebar *ngIf='messagebar' [hidden]='!messagebar.message'
[config]='messagebar'></messagebar>
    
    <div class='componentsContainer'>
      <div *ngFor='let component of dashboard.components;let i = index'
[ngSwitch]='component.type' [ngStyle]='component.layout'
        class='componentContainer' [contextMenu]='basicMenu'
[contextMenuSubject]='component'>
        <customtable *ngSwitchCase='"customtable"' [config]='component'
[componentId]='i' [container]='dashboard'></customtable>
        <grid *ngSwitchCase='"grid"' [config]='component' [componentId]='i'
[container]='dashboard'></grid>
        <heatmap *ngSwitchCase='"heatmap"' [config]='component'
[componentId]='i' [container]='dashboard'></heatmap>
        <gallery *ngSwitchCase='"gallery"' [config]='component'
[componentId]='i' [container]='dashboard'></gallery>
        <timeseries *ngSwitchCase='"timeseries"' [config]='component'
[componentId]='i' [container]='dashboard'></timeseries>
        <topn *ngSwitchCase='"topn"' [config]='component' [componentId]='i'
[container]='dashboard'></topn>
        <timeaxis *ngSwitchCase='"timeaxis"' [config]='component'
[componentId]='i' [container]='dashboard'></timeaxis>
        <mask *ngSwitchCase='"mask"' [config]='component' [componentId]='i'
[container]='dashboard'></mask>
        <context-menu #basicMenu>
          <template contextMenuItem (execute)="viewSource($event.item)">
            View Source
          </template>
          <template contextMenuItem let-item [enabled]="isHelpEnabled"
(execute)="openHelp($event.item)">
            Help
          </template>
          <template let-item='component' *ngFor='let action of
component.actions' contextMenuItem [enabled]='action.enabled'
[visible]='action.visible'
            (execute)='execute($event.item,action)'>
            {{ action.text }}
            </template>
        </context-menu>
    </div>
  </div>
  
  
  </div>
</body>


ComponentContainer class is absolute, other classes are using position fixed

**Comment by isaacplmann** [comment]
I’ll need to know which of those elements has a position style attribute set.

**Comment by spanda90** [comment]
every div has position:fixed , except for the one highlighted in yellow,
that has position:absolute

**Comment by spanda90** [comment]
If I place the context menu outside that div, it works fine.

**Comment by isaacplmann** [comment]
I can't reproduce your issue.  Can you send me all the styles of `.componentContainer`, `.componentsContainer` and `.dashboardContainer`?  There's probably something in there that is showing this bug.

**Comment by isaacplmann** [comment]
Also, what does `component.layout` look like?  What styles is it setting?

**Comment by spanda90** [comment]
@keyframes fadein {
  from {
    opacity: 0; }
  to {
    opacity: 1; } }

.dashboardContainer {
  font-family: Arial, sans-serif;
  width: 100%;
  height: 100%;
  position: fixed;
  background-color: black;
  color: white;
  animation: fadein 2s; }

.componentsContainer {
  position: fixed;
  bottom: 0;
  top: 30px;
  width: 100%; }

.componentContainer {
  overflow: auto;
  position: absolute; }

**Comment by spanda90** [comment]
"layout": {
                      "width": 98,
                      "height": 90,
                      "top": 2.5,
                      "left": 1
                    }

This is an example of component.layout

**Comment by spanda90** [comment]
Plus I had one more question, I was trying to override the existing styles and use custom styles but was not able to do so using the technique you mentioned in the document.

**Comment by spanda90** [comment]
I am using these styles: in my css 
.angular2-contextmenu .dropdown-menu {
  border: solid 1px chartreuse;
  background-color: darkgreen;
  padding: 0;
}
.angular2-contextmenu li {
  display: block;
  border-top: solid 1px chartreuse;
  text-transform: uppercase;
  text-align: center;
}
.angular2-contextmenu li:first-child {
  border-top:none;
}
.angular2-contextmenu a {
  color:chartreuse;
  display: block;
  padding: 0.5em 1em;
}
.angular2-contextmenu a:hover {
  color:darkgreen;
  background-color:chartreuse;
}

**Comment by isaacplmann** [comment]
Thanks for the styles.  I found a bug in my positioning logic.  I was checking for a style attribute on the element, but not checking the actual rendered style of the element (including stylesheets).

The bug will be fixed in the version I'll publish later today.

To style the context menu, make sure that you are doing one of the following:
1. Using `encapsulation: ViewEncapsulation.None` on your component
2. Putting the styles in a global css file
3. Add the `/deep/` or `>>>` before each rule

Any of those options should make your styles actually apply to the context menu.

**Comment by isaacplmann** [comment]
Try again with version 0.7.7

**Comment by isaacplmann** [comment]
Closing.  Open a new issue if something else comes up.

**Comment by spanda90** [comment]
Thanks this version fixed the problem
